name: docker-springcloud-msvc
services:
  config-server:
    container_name: config-server
    image: config-server:v1
    ports:
      - "8888:8888"
    restart: always
    networks:
      - springcloud

  eureka-server:
    container_name: eureka-server
    image: cjvaldi/eureka
    ports:
      - "8761:8761"
    restart: always
    networks:
      - springcloud

  mysql8:
    container_name: mysql8
    image: mysql:8
    command: --mysql-native-password=ON
    ports:
      - "3308:3306"
    restart: always
    networks:
      - springcloud
    environment:
      MYSQL_DATABASE: db_springboot_cloud
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      # - MYSQL_ROOT_PASSWORD=
  msvc-products:
    # container_name: msvc-products     // es opcional para la replica
    image: cjvaldi/products
    deploy:
      replicas: 3
    restart: always
    networks:
      - springcloud
    depends_on:
      - mysql8
      - eureka-server
  msvc-items:
    container_name: msvc-items
    image: cjvaldi/items
    restart: always
    ports:
      - "8002:8002"
      - "8005:8005"
      - "8007:8007"
    networks:
      - springcloud
    depends_on:
      - eureka-server
      - msvc-products

networks:
  springcloud:
      