spring.application.name=msvc-items
server.port=8002

# Spring Cloud Discovery Client Configuration
# spring.cloud.discovery.client.simple.instances.msvc-products[0].uri=http://localhost:8001
# spring.cloud.discovery.client.simple.instances.msvc-products[1].uri=http://localhost:9002

config.baseurl.endpoint.msvc-products=http://msvc-products

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka