spring.application.name=msvc-items
server.port=8005
configuracion.texto=Configurando ambiente de Produccion

# Configuración de URLs y clientes
config.baseurl.endpoint.msvc-products=http://msvc-products

# Configuración de Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka-server:8761/eureka}



