spring.application.name=config-server
server.port=8888

# spring.cloud.config.server.git.uri=file:///D:/01_Workspace/Learnig/spring-cloud-microservices/config
spring.cloud.config.server.git.uri=https://github.com/cjvaldi/msvc-config-server.git