spring.application.name=config-server
server.port=8888

# Hay que subir el repo para que funcione el config server
# el repo debe estar en la carpeta config del proyecto, y debe contener los archivos de propiedades de cada microservicio
# spring.cloud.config.server.git.uri=file:D:/01_Workspace/Learnig/spring-cloud-microservices/config/

spring.cloud.config.server.git.uri=file:///D:/01_Workspace/Learnig/spring-cloud-microservices
spring.cloud.config.server.git.search-paths=config
# spring.cloud.config.server.git.default-label=main
#Si tu rama se llama master, cambia:

# spring.profiles.active=native
# spring.cloud.config.server.native.search-locations=file:D:/01_Workspace/Learnig/spring-cloud-microservices/config/
